USE [master]
GO
IF DB_ID('BeanWater') IS NULL
	CREATE DATABASE [BeanWater]
GO
USE [BeanWater]
GO

DROP TABLE IF EXISTS [drinkTools]; 
DROP TABLE IF EXISTS [favorites];
DROP TABLE IF EXISTS [tools];
DROP TABLE IF EXISTS [drinks];
DROP TABLE IF EXISTS [drinkTypes];
DROP TABLE IF EXISTS [users];

CREATE TABLE [users] (
  [Id] int PRIMARY KEY identity NOT NULL,
  [Email] nvarchar(255),
  [displayName] nvarchar(255),
  [uId] nvarchar(255) NOT NULL UNIQUE,
)
GO

CREATE TABLE [drinks] (
  [Id] int PRIMARY KEY identity NOT NULL,
  [Name] nvarchar(255),
  [drinkTypesId] int,
  [drinksImg] nvarchar(255),
  [Recipe] varchar(8000)
)
GO

CREATE TABLE [drinkTypes] (
  [Id] int PRIMARY KEY identity NOT NULL,
  [Type] nvarchar(255)
)
GO

CREATE TABLE [tools] (
  [Id] int PRIMARY KEY identity NOT NULL,
  [Name] nvarchar(255),
  [Link] varchar(1080),
)
GO

CREATE TABLE [drinkTools] (
  [Id] int PRIMARY KEY identity NOT NULL,
  [drinkId] int,
  [toolId] integer
)
GO

CREATE TABLE [favorites] (
  [Id] int PRIMARY KEY identity NOT NULL,
  [drinkId] int,
  [uId] nvarchar(255)
)
GO

INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'Cappuccino',1,'https://globalassets.starbucks.com/assets/5c515339667943ce84dc56effdf5fc1b.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is a cappuccino?</h3><div>A cappuccino is an espresso drink with steamed milk, milk foam and espresso. It’s very similar to a latte (cafe latte), but the proportion of steamed milk is different. Here’s the breakdown of a latte vs cappuccino, a cappuccino has equal parts espresso, steamed milk and foam (1/3 each) whilst a latte is 1/3 espresso and 2/3 steamed milk, with a thin layer of foam on top.</div><h3>Ingredients</h3><ul><li>2 espresso shots (2 ounces)</li><li>4 ounces (1/2 cup) fresh whole milk*</li></ul><h3>Instructions</h3><ol><li><strong>Make the espresso:</strong> Use an espresso machine or manual espresso maker to make two shots of espresso and pour it into a mug.</li><li><strong>Steaming method (espresso machine):</strong> Place the milk in a pitcher. Hold the steaming wand just below the surface of the milk until it doubles in size and is very foamy. Lower the steaming wand slightly until the milk reaches 150 degrees Fahrenheit (use a thermometer or judge by when your hand can’t hold the pitcher for more than a few seconds).</li><li><strong>OR, heat the milk to scalding and foam it (without espresso machine):</strong> Heat the milk to 150 degrees Fahrenheit, which is hot to the touch but not simmering. Measure with a food thermometer, or you can approximate by testing with your finger. Use a milk frother, French press or whisk to froth the milk until it’s very foamy. For a cappuccino you’ll want a good amount of froth: you’re going for 1/3 espresso, 1/3 steamed milk and 1/3 foam. For the French press method, note that it’s useful to have at least 1 cup to have more milk to work with: this makes enough for 2 drinks.</li><li><strong>Serve:</strong>  Swirl the milk container a few times. Pour milk and foam into center of the espresso.</li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'Americano',1,'https://globalassets.starbucks.com/assets/f12bc8af498d45ed92c5d6f1dac64062.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is a Americano?</h3><div>An Americano is an espresso drink made with hot water and espresso, also called a Caffe Americano. The drink can be made with either one or two shots of espresso, and varying ratios of water. Diluting the strong dark espresso roast brings the flavor closer to a drip coffee.</div><h3>Ingredients</h3><ul><li>2 espresso shots (2 ounces)</li><li>4 ounces of water*</li></ul><h3>Instructions</h3><ol><li><strong>Make the espresso:</strong> Use an espresso machine or manual espresso maker to make two shots of espresso and pour it into a mug.</li><li><strong>Add hot water:</strong> Heat water using your espresso machine or in a tea pot to about 190 degrees Fahrenheit. Pour it into the espresso. Enjoy!</li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'Flat White',1,'https://globalassets.starbucks.com/assets/fedee22e49724cd09fbcc7ee2e567377.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is a Flat White?</h3><div>A flat white is a coffee drink with espresso, steamed milk and a layer of foam on top. It’s similar to a latte and cappuccino, but has a thinner layer of foam on top. Flat White is the least frothy, with about 1/4 inch microfoam at the top. The steamed milk is stretched 20-25%.</div><h3>Ingredients</h3><ul><li>2 espresso shots (2 ounces)</li><li>4 ounces (½ cup) fresh whole milk*</li></ul><h3>Instructions</h3><ol><li><strong>Make the espresso:</strong> Use an espresso machine or manual espresso maker to make two shots of espresso and pour it into a mug.</li><li><strong>Steaming method (espresso machine):</strong> Heat the steam wand. Once prepared, place the wand just below the surface of the milk about ½ inch from the side, tilting the jug slightly. Keep it in that position for about 5 to 10 seconds, stretching the milk by about 20 to 25% in height, with very slight movements up and down. Once stretched and slightly foamy, lower the nozzle about another 1/2 inch and tilt the pitcher just enough to get a spinning vortex, which incorporates the foam, turning it into a velvety microfoam. Keep that still and spinning until the temperature is about 150 degrees Fahrenheit. (Using a pitcher with a temperature sticker is very helpful.) Turn off the steam before removing the wand from the jug. Wipe the wand with a clean cloth. Turn it on for 1 second to purge the nozzle.  Tap and swirl the pitcher to incorporate any bubbles on top. The final texture should look like wet paint or melted ice cream, smooth and velvety. You’ll use only about half of this quantity and can discard the rest.</li><li><strong>OR, heat the milk to scalding and foam it (without espresso machine):</strong> Heat the milk to 150 degrees Fahrenheit, which is hot to the touch but not simmering. Measure with a food thermometer, or you can approximate by testing with your finger. Use a milk frother, French press or whisk to froth milk into small, even bubbles. For a latte you’ll want small bubbles and lightly thickened milk (if you’re using a milk frother, don’t go too far: you want the milk to mix in with the coffee so you don’t need too much froth**). For the French press method, note that it’s useful to have at least 1 cup to have more milk to work with: this makes enough for 2 drinks. Wait 30 seconds to 1 minute to get the foam to incorporate into the milk and separate slightly (exact timing depends on your foaming method).</li><li><strong>Serve:</strong>  Tap the milk container on counter and swirl it to break down any large bubbles. Pour milk into center of the espresso, ending with light foam.</li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'Latte',1,'https://globalassets.starbucks.com/assets/b635f407bbcd49e7b8dd9119ce33f76e.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is a Latte?</h3><div>A latte is a coffee drink with espresso, steamed milk and a layer of foam on top. What’s the difference between a latte vs a cappuccino? A cappuccino has equal parts espresso, steamed milk and foam (1/3 each). A latte has 1/3 espresso and 2/3 steamed milk, with a thin layer of foam on top. Oh, and a macchiato is just espresso with a thicker layer of foam on top.</div><h3>Ingredients</h3><ul><li>2 espresso shots (2 ounces)</li><li>4 ounces (1/2 cup) fresh whole milk*</li></ul><h3>Instructions</h3><ol><li><strong>Make the espresso:</strong> Use an espresso machine or manual espresso maker to make two shots of espresso and pour it into a mug.</li><li><strong>Steaming method (espresso machine):</strong> Place the milk in a pitcher. Hold the steaming wand just below the surface of the milk until it doubles in size. This makes foamy froth. Then, move the steaming wand lower and near the side of the pitcher to create a spiral vortex. This makes the silky smooth microfoam bubbles and wet-paint texture that’s characteristic of a latte. Steam until the milk reaches 150 degrees Fahrenheit (use a thermometer or judge by when your hand can’t hold the pitcher for more than a few seconds).</li><li><strong>OR, heat the milk to scalding and foam it (without espresso machine):</strong> Heat the milk to 150 degrees Fahrenheit, which is hot to the touch but not simmering. Measure with a food thermometer, or you can approximate by testing with your finger. Use a milk frother, French press or whisk to froth milk into small, even bubbles. For a latte you’ll want small bubbles and lightly thickened milk (if you’re using a milk frother, don’t go too far: you want the milk to mix in with the coffee so you don’t need too much froth). For the French press method, note that it’s useful to have at least 1 cup to have more milk to work with: this makes enough for 2 drinks. Wait 30 seconds to 1 minute to get the foam to incorporate into the milk and separate slightly (exact timing depends on your foaming method).</li><li><strong>Serve:</strong>  Tap the milk container on counter and swirl it to break down any large bubbles. Pour milk into center of the espresso, ending with light foam.</li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'Macchiato',1,'https://globalassets.starbucks.com/assets/26495f2a8b644fe8960dd74e1891b7b7.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is a Macchiato?</h3><div>A caffè macchiato or espresso macchiato is a shot of espresso topped with frothed milk. The word “macchiato” means “stained” in Italian, meaning that the dark espresso is stained by the milk foam on top.</div><h3>Ingredients</h3><ul><li>2 espresso shots (2 ounces)</li><li>2 ounces (1/4 cup) fresh whole milk*</li></ul><h3>Instructions</h3><ol><li><strong>Make the espresso:</strong> Use an espresso machine or manual espresso maker to make two shots of espresso and pour it into a mug.</li><li><strong>Steam the milk (espresso machine) or heat the milk to scalding:</strong> Start with 1/2 cup milk (you’ll only use ¼ cup foam.) Heat the milk to 150 degrees Fahrenheit, which is hot to the touch but not simmering. Measure with a food thermometer, or you can approximate by testing with your finger.</li><li><strong>Froth the milk:</strong> Use the espresso machine or a milk frother, French press or whisk to froth milk into small, even bubbles. You’ll want lots of “dry foam” for a macchiato: the fluffy stuff! The milk frother is great for this type of foam. </li><li><strong>Spoon the foam on top:</strong> Use a spoon to remove the top of the foam (dry foam) and gently place it on top of the espresso. You should use about 1/4 cup foam for one drink.</li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'Mocha',1,'https://globalassets.starbucks.com/assets/915736da018842e788147f7eab73db73.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is a Mocha?</h3><div>A mocha or mocha latte is a drink made with espresso and steamed milk that’s flavored with chocolate syrup. There’s lots of variation on exactly what constitutes this espresso drink: it’s up to the barista! This drink can be made with various levels of espresso shots, quantities of steamed milk, and amounts of chocolate syrup.</div><h3>Ingredients</h3><ul><li>2 espresso shots (2 ounces)</li><li>4 ounces (1/2 cup) fresh whole milk*</li><li>1 tablespoon chocolate chips</li><li>½ tablespoon maple syrup (or simple syrup)</li><li>For the garnish: chocolate shavings</li></ul><h3>Instructions</h3><ol><li><strong>Make the espresso:</strong> Use an espresso machine or manual espresso maker to make two shots of espresso and pour it into a mug.</li><li><strong>Steam the milk (espresso machine):</strong> Place the milk and syrup in a pitcher. Hold the steaming wand just below the surface of the milk until it doubles in size and is very foamy. Lower the steaming wand slightly until the milk reaches 150 degrees Fahrenheit (use a thermometer or judge by when your hand can’t hold the pitcher for more than a few seconds).</li><li><strong>Foaming method (without espresso machine):</strong> Heat the milk and syrup to 150 degrees Fahrenheit, which is “scalding”: hot to the touch but not simmering. Measure with a food thermometer, or you can approximate by testing with your finger. Use a milk frother, French press or whisk to froth the milk until it’s very foamy (or shake it in a covered jar). For a mocha you’ll want a good amount of froth. For the French press method, note that it’s useful to have at least 1 cup to have more milk to work with: this makes enough for 2 drinks.</li><li><strong>Serve:</strong> Swirl the milk container a few times. Pour milk and foam into center of the chocolaty espresso. If desired, top with chocolate shavings for garnish.</li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'White Mocha',1,'https://globalassets.starbucks.com/assets/3eab25199e994b689fa5c047fc31f217.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is a White Mocha?</h3><div>A white mocha or white mocha latte is a drink made with espresso and steamed milk that’s flavored with white chocolate syrup. There’s lots of variation on exactly what constitutes this espresso drink: it’s up to the barista! This drink can be made with various levels of espresso shots, quantities of steamed milk, and amounts of white chocolate syrup.</div><h3>Ingredients</h3><ul><li>2 espresso shots (2 ounces)</li><li>4 ounces (1/2 cup) fresh whole milk*</li><li>1 tablespoon white chocolate chips</li><li>½ tablespoon maple syrup (or simple syrup)</li><li>For the garnish: chocolate shavings</li></ul><h3>Instructions</h3><ol><li><strong>Make the espresso:</strong> Use an espresso machine or manual espresso maker to make two shots of espresso. Place the chocolate chips into the mug and pour the espresso on top.</li><li><strong>Steam the milk (espresso machine):</strong> Place the milk and syrup in a pitcher. Hold the steaming wand just below the surface of the milk until it doubles in size and is very foamy. Lower the steaming wand slightly until the milk reaches 150 degrees Fahrenheit (use a thermometer or judge by when your hand can’t hold the pitcher for more than a few seconds).</li><li><strong>Foaming method (without espresso machine):</strong> Heat the milk and syrup to 150 degrees Fahrenheit, which is “scalding”: hot to the touch but not simmering. Measure with a food thermometer, or you can approximate by testing with your finger. Use a milk frother, French press or whisk to froth the milk until it’s very foamy (or shake it in a covered jar). For a mocha you’ll want a good amount of froth. For the French press method, note that it’s useful to have at least 1 cup to have more milk to work with: this makes enough for 2 drinks.</li><li><strong>Serve:</strong> Swirl the milk container a few times. Pour milk and foam into center of the chocolaty espresso. If desired, top with chocolate shavings for garnish.</li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'Hot Chocolate',2,'https://globalassets.starbucks.com/assets/677d276173ec4bc192c2b9a21776339f.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is a Hot Chocolate?</h3><div>Hot chocolate, also known as hot cocoa or drinking chocolate, is a heated drink consisting of shaved or melted chocolate or cocoa powder, heated milk or water, and usually a sweetener. It is often garnished with whipped cream or marshmallows.</div><h3>Ingredients</h3><ul><li>3 tablespoons cocoa powder</li><li>2 cups 2% milk (or oat milk)</li><li>3 tablespoons sugar</li><li>¼ teaspoon vanilla extract</li><li>1 pinch cinnamons</li><li>¼ cup (1 ½ ounces) semisweet or dark chocolate chips</li></ul><h3>Instructions</h3><ol><li>Place a saucepan over medium heat. Add the cocoa powder and ¼ cup of the milk and whisk until the cocoa powder is mostly integrated. Whisk in the remaining milk until smooth.</li><li>Add the remaining ingredients and heat over medium heat until the chocolate is melted, about 2 minutes. Do not boil. Serve immediately, garnished with whipped cream or marshmallows.</li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'Caramel Apple Spice',2,'https://globalassets.starbucks.com/assets/39bab62a29214270b6b30eb838e2c5a6.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is a Carmel Apple Spice?</h3><div>Steamed apple juice complemented with cinnamon syrup, whipped cream and a caramel sauce drizzle.</div><h3>Ingredients</h3><ul><li>2 cups apple juice or apple cider</li><li>2 tablespoon cinnamon dolce syrup (recipe below)</li><li>2 tablespoons caramel sauce</li><li>Whipped cream</li><li>1/2 cup water</li><li>1/4 cup brown sugar</li><liv>2 tablespoons granulated sugar</liv><liv>1/2 teaspoon ground cinnamon</liv><liv>2 teaspoons vanilla extract</liv></ul><h3>Instructions</h3><ol><li>To make the cinnamon dolce syrup, bring the water and sugars to a soft boil until the sugar melts, continuously stirring. Add in cinnamon and vanilla and let cook for about 3-5 more minutes. It should be about a syrupy consistency. Once cool, refridgerate until ready to use.</li><li>In a medium saucepan, combine apple juice, cinnamon dolce syrup, and caramel sauce over medium heat. Cook for about 3-5 minutes or until everything has combined well and warmed up.</li><li>Divide into two cups and top with whipped cream and additional caramel.</li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'Chai tea latte',5,'https://globalassets.starbucks.com/assets/2d52f16a22fb40ff898be1815ecc952e.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is a Carmel Apple Spice?</h3><div>A chai latte takes traditional masala chai, a milky spiced tea from India, and combines it with frothy steamed milk of a cafe latte. The mashup appears to be an American invention that was popularized by Starbucks in the 1990’s.</div><h3>Ingredients</h3><ul><li>1 teaspoon Homemade Chai Spices</li><li>1 cup water</li><li>1 bag black tea (or 1 teaspoon loose leaf black tea in a tea strainer)</li><li>½ cup fresh 2% milk (or whole milk)*</li><li>1 tablespoon pure maple syrup (or simple syrup)</li></ul><h3>Instructions</h3><ol><li>In a small saucepan over medium high heat, whisk together chai spices, water and tea bag and bring to a boil. Once boiling, remove it from the heat and allow it to rest for 1 minute. Then strain through a fine mesh strainer** into one or two mugs (one for a large latte and two for small).</li><li>Rinse the saucepan. Add the milk and maple syrup. Heat the milk to 150 degrees Fahrenheit (measure using a thermometer): this is hot with some small bubbles forming around the outside, but not simmering. The exact temperature is helpful for getting the perfect foam (if you don’t have a thermometer you can approximate).</li><li>Use hand frother, whisk, or french press to foam the milk. (The french press is our favorite method: Add the scalding milk to the french press and pump vigorously until frothy, about 100 times for 2% milk or approximately 1 minute; use 50 times for whole milk.) Rest the foam for about 30 seconds, which allows it to set.</li><li>Pour the milk and foam evenly between the mugs (or into 1 mug). Sprinkle with additional chai spices and serve.</li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'London Fog',5,'https://globalassets.starbucks.com/assets/180da7ecb6fa4d2686babe5619fa7b84.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is a Carmel Apple Spice?</h3><div>A London fog is a hot tea-based drink that consists of Earl Grey tea, steamed milk, and vanilla syrup.</div><h3>Ingredients</h3><ul><li>1 Earl Grey tea bag</li><li>1/2 cup hot water</li><li>1/2 of milk</li><li>1/4 tsp vanilla extract</li><li>1–2 tsp raw honey, maple syrup or sweetener of choice</li></ul><h3>Instructions</h3><ol><li>Steep your tea bag in 1/2 cup of hot water for 3-5 mins (depending on strength preference)</li><li>Mix together almond milk and vanilla extract and steam or froth.</li><li>Stir sweetener in with steeped tea and top with frothed milk.</li><li>Enjoy hot!</li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'Honey Citrus Mint Tea',5,'https://globalassets.starbucks.com/assets/a5e64777b3cc412e9239b8a37328cb37.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is a Honey Citrus Mint Tea?</h3><div>This recipe is for the copycat Starbucks medicine ball tea (AKA the Starbucks coldbuster) will soothe all the colds and aches during the cold seasons. Serve it hot with plenty of honey to boost your immune system.</div><h3>Ingredients</h3><ul><li>1 ½ cup lemonade</li><li>1 sachet Teavana Jade Citrus Mint Tea</li><li>1 sachet Teavana Peach Tranquility Tea</li><li>1 tablespoon honey</li><li>2-3 drops peppermint extract (optional)</li></ul><h3>Instructions</h3><ol><li>Steam lemonade in either an electric tea kettle set to 185 degrees F or on the stovetop in a saucepan (measure temperature with a thermometer) over medium heat. Once at temperature, remove the lemonade from the heat and into a large mug.</li><li>Optional: Once heated: use a milk frother or the steam wand on your espresso maker to froth the lemonade.</li><li>Steep the two tea bags in the hot lemonade: the green tea for 3 minutes, the peach tea for 5 minutes.</li><li>Stir in the honey until fully incorporated into the tea.</li><li>Enjoy hot!</li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'Chocolate Java Mint',3,'https://globalassets.starbucks.com/assets/7FD73D3C93AF43FFA84400A42EFC9F87.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is a Chocolate Java Mint?</h3><div>Coffee and flavors of sweet chocolate and refreshing mint blended with rich Frappuccino® chips for a smooth treat finished with a layer of mocha sauce, whipped cream and chocolate-mint cookie crumble.</div><h3>Ingredients</h3><ul><li>1 cup strong brewed coffee</li><li>2 cups ice cubes</li><li>1 cup milk</li><li>4 tablespoons chocolate chips</li><li>4 tablespoons chocolate sauce</li><li>whipped cream</li></ul><h3>Instructions</h3><ol><li>Prepare your coffee roast (brewed coffee or instant coffee) and let it chill in the refrigerator.</li><li>Loosely drizzle chocolate sauce inside of each glass and set aside. You can place the drizzled glasses in the freezer.</li><li>Add ice, coffee roast, milk, chocolate sauce, and chocolate chip into a blender.</li><li>Secure the lid and start to blend on low speed for about 30 seconds, and then on a max speed for about 20 seconds or until the mixture is evenly smooth. (Taste test your drink, if you would like to make it thicker, you can add more ice cubes and blend again.)</li><li>Pour into individual glasses and top with whipped cream. Drizzle with chocolate sauce.</li><li>Serve and enjoy this creamy and delicious coffee drink immediately.</li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'Mocha Cookie Crumble',3,'https://globalassets.starbucks.com/assets/1fd99578d31f4072a52892398d8f1fa8.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is a Mocha Cookie Crumble?</h3><div>When a plain mocha frappuccino isn’t enough to hit the spot, the added bonus of Oreo sandwich cookies saves the day, adding an extra layer of chocolate goodness that you didn’t even know you needed.</div><h3>Ingredients</h3><ul><li>1 cup strong brewed coffee</li><li>2 cups ice cubes</li><li>1/2 cup milkk</li><li>1/2 cup of chocolate chips</li><li>4 tablespoons chocolate sauce</li><li>8 crushed Oreo cookies</li><li>whipped cream</li></ul><h3>Instructions</h3><ol><li>Start by brewing a cup of your favorite strong coffee or a shot of espresso; for a better-tasting result, you’ll want it to be as fresh as possible, so consider grinding your own beans for your brew.</li><li>Then, add the crushed Oreos (save a few cookie crumbs — you’ll need them later!), chocolate chips, milk, chocolate syrup, and coffee to the blender and pulse until the mixture is smooth. Feel free to use whatever milk you prefer; whether you opt to use whole milk or vegan-friendly nut milk, the mocha cookie crumble frappuccino will still be creamy and delicious.</li><li>Once your mixture is evenly blended, add your ice to the blender. Remember, the amount of ice you use will determine how thick your drink will be, so keep that in mind as you decide whether one cup or two is best. Blend until the mixture thickens.</li><li>Pour your blended coffee drink into a glass, and top it with whipped cream and crushed Oreo cookies. For an extra burst of sweet goodness, drizzle a bit of chocolate syrup on top of it, too — absolutely delicious.</li><li>Serve and enjoy this creamy and delicious coffee drink immediately.</li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'Carmel Frappuccino',3,'https://globalassets.starbucks.com/assets/410cd92738514641bf497d4b6a18c30f.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is a Carmel Frappuccino?</h3><div>Caramel Frappuccino is made by blending espresso with caramel syrup, milk, and ice until it becomes a chunky, icy drink. A swirl of whipped cream on top gives it a decadent finish, along with a drizzle of caramel sauce.</div><h3>Ingredients</h3><ul><li>1 cup strong brewed coffee</li><li>2 tablespoons caramel syrup</li><li>1 cup milk</li><li>1-2 cups ice</li><li>2 tablespoons whipped cream</li><li>1 tablespoon caramel sauce</li></ul><h3>Instructions</h3><ol><li>Place coffee and milk in a blender.</li><li>Add caramel syrup and ice. Blend until smooth.</li><li>Drizzle caramel sauce around the inside of a glass if desired.</li><li>Pour the blended frappuccino into the glass.</li><li>Top with whipped cream and caramel sauce. Enjoy!</li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'Vanilla Bean Frappuccino',3,'https://globalassets.starbucks.com/assets/b8f963bfe65b4117af17d316e6bc3bc8.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is a Vanilla Bean Frappuccino?</h3><div>A Frappuccino is a cold blended coffee drink that is made with either coffee or a crème base (like ice cream).  So you can make a coffee Frappuccino or a crème Frappuccino. This Vanilla Bean Frappe is a crème base Frappuccino as it’s made with ice cream and not made with coffee so I don’t feel guilty when I give these to my kids.</div><h3>Ingredients</h3><ul><li>1 cup Ice</li><li>1 1/2 cup Milk</li><li>3 scoops Vanilla Bean Ice Cream</li><li>1 tsp Sugar/li><li>1/8 tsp Vanilla Extract</li><li>Whipped Cream optional</li></ul><h3>Instructions</h3><ol><li>Blend all ingredients except whipped cream until blended.</li><li>Transfer to serving glass and top with whipped cream.</li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'Mocha Frappuccino',3,'https://globalassets.starbucks.com/assets/70198375bb0a442f8792437b5d1df972.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is a Mocha Frappuccino?</h3><div>Frappucinos are iced, blended drinks trademarked by Starbucks that can be made with or without coffee. This cold and refreshing drink has espresso in it, so it will give you a boost of energy from caffeine. With the added chocolate syrup, you will get that mocha flavor in every sip!.</div><h3>Ingredients</h3><ul><li>2 cups ice</li><li>4 shots espresso</li><li>1/2 cup chocolate syrup, plus extra for topping</li><li>¼ cup whole milk/li><li>3 tablespoons granulated sugar</li><li>whipped cream, or cool whip for topping</li></ul><h3>Instructions</h3><ol><li>Add ice, espresso, chocolate syrup, milk, and sugar to a blender and puree until smooth.</li><li>Pour equally into two tall glasses.</li><li>Top each drink with whipped cream and more chocolate syrup.</li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'Cold Brew',4,'https://globalassets.starbucks.com/assets/103b2b745f4848f884b793696a4573b6.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is Cold Brew?</h3><div> Cold brew coffee is coffee made by soaking the grounds in water at cool temperatures. It’s different from drip or brewed coffee that’s made by percolating hot water over coffee grounds in a filter. Cold brew has become very popular at coffeeshops because of its deliciously smooth flavor.</div><h3>Ingredients</h3><ul><li>1 1/2 cups dark roast coffee, medium coarse ground</li><li>6 cups room temperature filtered water</li><li>French Press</li></ul><h3>Instructions</h3><ol><li><strong>Grind the coffee:</strong> Grind the coffee to a medium coarse grind.</li><li><strong>Mix coffee ground and water:</strong> Place the water in a french press. Add the coffee grounds to the water. Press together.</li><li><strong>Refrigerate 24 hours:</strong> Leave out or refrigerate the cold brew for 24 hours</li><li><strong>Strain the coffee:</strong> Strain the coffee into a clean container. Discard all coffee grounds. Place the cold brew concentrate back into the pitcher and refrigerate. Store refrigerated up to 1 week.</li><li><strong>Serve:</strong> To serve, dilute 1/2 cup cold brew concentrate with 1/2 cup water. If serving with ice, use the ice with 1/2 cup cold brew concentrate with 1/4 cup water. </li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'Nitro Cold Brew',4,'https://globalassets.starbucks.com/assets/8c5dcfa053504f85b3e7af2fa451346d.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is Nitro Cold Brew?</h3><div>Nitro cold brew is small-batch cold brew—slow-steeped for a super-smooth taste—gets even better. Nitro is infused with nitrogen to create a sweet flavor without sugar and cascading, velvety crema. Perfection is served.</div><h3>Ingredients</h3><ul><li>16 ounces of coffee concentrate</li><li>32 ounces of water</li><li>French Press</li><li>Nitro cold brew kit</li><li>Nitrogen cartridges</li></ul><h3>Instructions</h3><ol><li><strong>Cold brew:</strong> If you are brewing your own cold brew, you should do the following ratio: 7 oz of Ground Coffee *to* 28 oz of water = yields = 16 ounces of coffee concentrate. Then, add 32 ounces of water to the concentrate, and you will have a perfect 48 ounces of cold brew in your 64 oz keg. Please see the Cold Brew section for info on how to make cold brew.</li><li><strong>Add cold brew coffee to the keg:</strong> Important: To allow gas to form, only fill the keg up to 50%-75% maximum with coffee!</li><li><strong>Install the faucet:</strong> Attach plastic hose to the bottom of the spear, and attach faucet to spear. Note: do not overtighten spear onto keg, for easier removal after batch. Use wrench to tighten faucet onto spear. Be sure plastic hose is cut to 20cm maximum for 64 oz keg! (usually is pre-cut)</li><li><strong>Put the nitrogen capsules in nitrogen jacket:</strong> If using N2O Nitrous Oxide Cartridges, you only need to use one per batch, use FOMAGAS Nitrous Oxide cartridges or any 8g Nitrous Oxide cartridge</li><li><strong>Tighen nitro jacket:</strong>Screw in the nitrogen jacket until you hear a hissing noise.</li><li><strong>Shake growler:</strong>Shake the growler well, then, put it in refrigerator for more than 1 hour.</li><li><strong>Serve:</strong>Enjoy your nitro cold brew coffee!</li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'Iced Latte',4,'https://globalassets.starbucks.com/assets/f4fd128c834643fa8c74f4ae9f579013.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is a Iced Latte?</h3><div>An iced latte is a drink with espresso, milk and optional sweetener. The milk is often frothed to simulate the steamed milk in a standard latte.</div><h3>Ingredients</h3><ul><li>2 shots espresso (2 ounces)</li><li>1 teaspoon maple syrup (or simple syrup)</li><li>¼ cup whole milk</li><li>Ice</li></ul><h3>Instructions</h3><ol><li><strong>Make the espresso:</strong> Make the espresso using an espresso machine.</li><li><strong>Froth the milk:</strong> Use a handheld milk frother, which makes the frothiest milk. Place the milk in a tall container. Hold the container at an angle and turn on the frother. Move the frother up and down until foamy bubbles form, about 20 seconds or so. It’s easiest to use at least 1/2 cup milk (use the remainder for another iced latte).</li><li><strong>Serve:</strong> Add the espresso to ice-filled glass. Stir in the maple syrup and top with the frothed milk. Enjoy immediately.</li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'Iced Mocha',4,'https://globalassets.starbucks.com/assets/0360378c6e774cc3a38d870fc75d5462.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is a Iced Mocha?</h3><div>An iced mocha is a coffee drink made with espresso, milk and chocolate, served over ice. It’s a variation on the hot mocha or mocha latte, a drink made with espresso, steamed milk and chocolate.</div><h3>Ingredients</h3><ul><li>2 shots espresso (2 ounces)</li><li>1 tablespoon chocolate chips (or white chocolate chips for an Iced White Chocolate Mocha)</li><li>1 teaspoon chocolate syrup (or simple syrup)</li><li>¼ cup whole milk</li><li>Ice</li></ul><h3>Instructions</h3><ol><li><strong>Make the espresso:</strong> Make the espresso using an espresso machine.</li><li><strong>Shake:</strong> Place the hot espresso and chocolate chips in a covered jar: vigorously shake until melted. Pour into an ice filled glass.</li><li><strong>Froth the milk:</strong> Rinse out the jar. Place the milk and simple syrup back into the jar, cover and shake until foamy.</li><li><strong>Serve:</strong> Top the chocolate espresso with the frothed milk. Enjoy immediately.</li></ol>')
INSERT INTO dbo.[drinks]([Name],[drinkTypesId],[drinksImg],[Recipe]) VALUES ( 'Iced Flat White',4,'https://globalassets.starbucks.com/assets/a1d7c679325f4c32ab5441f051aa0767.jpg?impolicy=1by1_wide_topcrop_630','<h3>What is an Iced Flat White?</h3><div>An iced flat white is a coffee beverage made with ristretto, cold foamed milk and served on ice. The iced flat white is very similar to an iced latte, except that the milk is steamed in an espresso machine, not frothed.</div><h3>Ingredients</h3><ul><li>2 shots espresso (2 ounces)</li><li>1 cup of milk</li><li>1 teaspoon simple syrup or maple syrup</li><li>Ice</li></ul><h3>Instructions</h3><ol><li>Start by cold foaming your milk. You can do so by adding your milk to a milk frother.</li><li>While the milk is foaming up, start brewing your ristretto shots.</li><li>Fill a glass with ice cubes and make sure there is enough in there to cool your coffee completely.</li><li>Now, add your coffee to the ice cubes and stir it. This will help cool down the coffee before adding the milk.</li><li>Top the iced coffee with your cold foamed milk, and make sure to use as many of those small bubbles that make the flat white so unique.</li><li>Optionally, you can add some sweetener to your coffee. Stir your coffee and enjoy!</li></ol>')
INSERT INTO dbo.drinkTypes([Type]) VALUES ( 'Hot Coffees')
INSERT INTO dbo.drinkTypes([Type]) VALUES ( 'Hot Drinks')
INSERT INTO dbo.drinkTypes([Type]) VALUES ( 'Frappuccinos')
INSERT INTO dbo.drinkTypes([Type]) VALUES ( 'Cold coffees')
INSERT INTO dbo.drinkTypes([Type]) VALUES ( 'Teas')

INSERT INTO dbo.users([displayName],[Email],[uId]) VALUES ( 'Jayla', 'ibjaylacook@yahoo.com', 'IIrurrqM5dMonkoiI7pdpqSweuL2')

INSERT INTO dbo.favorites([drinkId],[uId] ) VALUES ( 1,'IIrurrqM5dMonkoiI7pdpqSweuL2')

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 1,1)/*Cappuccino*/
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 1,2)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 1,3)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 1,4)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 1,5)

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 2,1)/*Americano*/
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 2,2)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 2,3)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 2,5)

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 3,1)/*Flat White*/
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 3,2)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 3,3)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 3,4)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 3,5)

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 4,1)/*Latte*/
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 4,2)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 4,3)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 4,4)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 4,5)

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 5,1)/*Macchiato*/
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 5,2)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 5,3)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 5,4)

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 6,1)/*Mocha*/
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 6,2)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 6,3)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 6,4)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 6,5)

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 7,1)/*White Mocha*/
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 7,2)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 7,3)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 7,4)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 7,5)

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 8,4)/*Hot Chocolate*/

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 9,4)/*Caramel Apple Spice*/

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 10,4)/*Chai tea latte*/

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 11,4)/*London Fog*/

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 13,6) /*Java Chip*/
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 13,7)

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 14,6) /*Mocha Cookie Crumble*/
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 14,7)

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 15,6) /*Carmel Frappuccino*/
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 15,7)

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 16,6) /*Vanilla bean Frappuccino*/

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 17,6) /*Mocha Frappuccino*/
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 17,1)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 17,2)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 17,3)

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 18,5) /*Cold Brew*/

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 19,5) /*Nitro Cold Brew*/
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 19,8) 

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 20,1)/*Iced Latte*/
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 20,2)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 20,3)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 20,4)

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 21,1)/*Iced Mocha*/
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 21,2)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 21,3)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 21,4)

INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 22,1)/*Iced Flat White*/
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 22,2)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 22,3)
INSERT INTO dbo.drinkTools([drinkId],[toolId] ) VALUES ( 22,4)

INSERT INTO dbo.tools([Name],[Link]) VALUES ( 'Auto Esspresso Maker', 'https://www.amazon.com/IMUSA-USA-GAU-18202-Cappuccino-Cappuccion/dp/B07L85NN3T/ref=sr_1_6?crid=15WR5CY0JPH5O&keywords=espresso+maker&qid=1684597892&sprefix=espresso+maker+%2Caps%2C88&sr=8-6')
INSERT INTO dbo.tools([Name],[Link]) VALUES ( 'Manuel Esspresso Maker', 'https://www.amazon.com/gp/product/B07D53TTFD/ref=ppx_yo_dt_b_asin_title_o08_s00?ie=UTF8&tag=acouplecook-1-bg-20&th=1')
INSERT INTO dbo.tools([Name],[Link]) VALUES ( 'Pod Esspresso Maker', 'https://www.amazon.com/Nespresso-Essenza-Original-Espresso-Breville/dp/B073ZGWN12/ref=sr_1_5?keywords=nespresso+machine&qid=1684598084&sprefix=nespresso+m%2Caps%2C82&sr=8-5')
INSERT INTO dbo.tools([Name],[Link]) VALUES ( 'Milk Frother', 'https://www.amazon.com/gp/product/B0BBHB1DDZ/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&tag=acouplecook-1-bg-20&th=1')
INSERT INTO dbo.tools([Name],[Link]) VALUES ( 'French press/Tea maker', 'https://www.amazon.com/BAYKA-French-Press-Double-Wall-Filtration/dp/B07RXW7ZJQ/ref=sr_1_3_sspa?dchild=1&keywords=french%2Bpress&qid=1603226597&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFPUDZQTkVFSjVXWE8mZW5jcnlwdGVkSWQ9QTAyMDAyNTkyWEFLQVpNNjUyQVU5JmVuY3J5cHRlZEFkSWQ9QTEwMzE4MThRU082Q1dRUzVPSDMmd2lkZ2V0TmFtZT1zcF9hdGYmYWN0aW9uPWNsaWNrUmVkaXJlY3QmZG9Ob3RMb2dDbGljaz10cnVl&sr=8-3-spons&tag=acouplecook-1-bg-20&th=1')
INSERT INTO dbo.tools([Name],[Link]) VALUES ( 'Blender', 'https://www.amazon.com/NutriBullet-NBF40500-nutribullet-Blender-Silver/dp/B0B7R3VVC4?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A3LJ2FXZPL0RZH')
INSERT INTO dbo.tools([Name],[Link]) VALUES ( 'Blender/Coffee maker', 'https://www.amazon.com/Mr-Coffee-Single-Serve-Blender-Reusable/dp/B09JZR6XWC/ref=sr_1_8?crid=2RL61PUON0FL1&keywords=blender+coffee+maker&qid=1684605500&sprefix=blender+coffee+maker%2Caps%2C91&sr=8-8')
INSERT INTO dbo.tools([Name],[Link]) VALUES ( 'Nitro Cold Brew Kit', 'https://www.amazon.com/Royal-Nitro-Coffee-Maker-System/dp/B07SB2K1C6?th=1')

ALTER TABLE [favorites] ADD FOREIGN KEY ([uId]) REFERENCES [users] ([uId])
GO

ALTER TABLE [favorites] ADD FOREIGN KEY ([drinkId]) REFERENCES [drinks] ([Id])
GO

ALTER TABLE [drinks] ADD FOREIGN KEY ([drinkTypesId]) REFERENCES [drinkTypes] ([Id])
GO

ALTER TABLE [drinkTools] ADD FOREIGN KEY ([toolId]) REFERENCES [tools] ([Id])
GO

ALTER TABLE [drinkTools] ADD FOREIGN KEY ([drinkId]) REFERENCES [drinks] ([Id])
GO
